import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import KakaoSDK from "@/components/KakaoSDK";

export const metadata: Metadata = {
  title: "Notification App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="ko">
      <KakaoSDK>
        <Providers >
          <body>{children}</body>
        </Providers>
      </KakaoSDK>
    </html>
  );
}
